---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (unknown)
  creationTimestamp: null
  name: netdnses.kdoctor.io
spec:
  group: kdoctor.io
  names:
    categories:
    - kdoctor
    kind: Netdns
    listKind: NetdnsList
    plural: netdnses
    singular: netdns
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: finish
      jsonPath: .status.finish
      name: finish
      type: boolean
    - description: expectedRound
      jsonPath: .status.expectedRound
      name: expectedRound
      type: integer
    - description: doneRound
      jsonPath: .status.doneRound
      name: doneRound
      type: integer
    - description: lastRoundStatus
      jsonPath: .status.lastRoundStatus
      name: lastRoundStatus
      type: string
    - description: schedule
      jsonPath: .spec.schedule.schedule
      name: schedule
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              expect:
                properties:
                  meanAccessDelayInMs:
                    default: 5000
                    format: int64
                    minimum: 1
                    type: integer
                  statusCode:
                    maximum: 599
                    minimum: 100
                    type: integer
                  successRate:
                    default: 1
                    maximum: 1
                    minimum: 0
                    type: number
                type: object
              request:
                properties:
                  domain:
                    default: kubernetes.default.svc.cluster.local
                    type: string
                  durationInSecond:
                    default: 2
                    format: int64
                    minimum: 1
                    type: integer
                  perRequestTimeoutInMS:
                    default: 5
                    format: int64
                    minimum: 1
                    type: integer
                  protocol:
                    default: udp
                    enum:
                    - udp
                    - tcp
                    - tcp-tls
                    type: string
                  qps:
                    default: 5
                    format: int64
                    minimum: 1
                    type: integer
                type: object
              schedule:
                properties:
                  roundNumber:
                    default: 1
                    format: int64
                    minimum: -1
                    type: integer
                  roundTimeoutMinute:
                    default: 60
                    format: int64
                    minimum: 1
                    type: integer
                  schedule:
                    type: string
                required:
                - roundNumber
                - roundTimeoutMinute
                type: object
              sourceAgentNodeSelector:
                description: A label selector is a label query over a set of resources.
                  The result of matchLabels and matchExpressions are ANDed. An empty
                  label selector matches all objects. A null label selector matches
                  no objects.
                properties:
                  matchExpressions:
                    description: matchExpressions is a list of label selector requirements.
                      The requirements are ANDed.
                    items:
                      description: A label selector requirement is a selector that
                        contains values, a key, and an operator that relates the key
                        and values.
                      properties:
                        key:
                          description: key is the label key that the selector applies
                            to.
                          type: string
                        operator:
                          description: operator represents a key's relationship to
                            a set of values. Valid operators are In, NotIn, Exists
                            and DoesNotExist.
                          type: string
                        values:
                          description: values is an array of string values. If the
                            operator is In or NotIn, the values array must be non-empty.
                            If the operator is Exists or DoesNotExist, the values
                            array must be empty. This array is replaced during a strategic
                            merge patch.
                          items:
                            type: string
                          type: array
                      required:
                      - key
                      - operator
                      type: object
                    type: array
                  matchLabels:
                    additionalProperties:
                      type: string
                    description: matchLabels is a map of {key,value} pairs. A single
                      {key,value} in the matchLabels map is equivalent to an element
                      of matchExpressions, whose key field is "key", the operator
                      is "In", and the values array contains only "value". The requirements
                      are ANDed.
                    type: object
                type: object
                x-kubernetes-map-type: atomic
              target:
                properties:
                  enableLatencyMetric:
                    default: false
                    type: boolean
                  targetDns:
                    properties:
                      serviceName:
                        type: string
                      serviceNamespace:
                        type: string
                      testIPv4:
                        default: true
                        type: boolean
                      testIPv6:
                        default: false
                        type: boolean
                    type: object
                  targetUser:
                    properties:
                      port:
                        default: 53
                        type: integer
                      server:
                        type: string
                    type: object
                type: object
            type: object
          status:
            properties:
              doneRound:
                format: int64
                minimum: 0
                type: integer
              expectedRound:
                format: int64
                minimum: -1
                type: integer
              finish:
                type: boolean
              history:
                items:
                  properties:
                    deadLineTimeStamp:
                      format: date-time
                      type: string
                    duration:
                      type: string
                    endTimeStamp:
                      format: date-time
                      type: string
                    expectedActorNumber:
                      description: expected how many agents should involve
                      type: integer
                    failedAgentNodeList:
                      items:
                        type: string
                      type: array
                    failureReason:
                      type: string
                    notReportAgentNodeList:
                      items:
                        type: string
                      type: array
                    roundNumber:
                      type: integer
                    startTimeStamp:
                      format: date-time
                      type: string
                    status:
                      enum:
                      - succeed
                      - fail
                      - ongoing
                      - notstarted
                      type: string
                    succeedAgentNodeList:
                      items:
                        type: string
                      type: array
                  required:
                  - deadLineTimeStamp
                  - failedAgentNodeList
                  - notReportAgentNodeList
                  - roundNumber
                  - startTimeStamp
                  - status
                  - succeedAgentNodeList
                  type: object
                type: array
              lastRoundStatus:
                enum:
                - succeed
                - fail
                - unknown
                type: string
            required:
            - finish
            - history
            type: object
        required:
        - metadata
        type: object
    served: true
    storage: true
    subresources:
      status: {}
