---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (unknown)
  creationTimestamp: null
  name: netreaches.kdoctor.io
spec:
  group: kdoctor.io
  names:
    categories:
    - kdoctor
    kind: NetReach
    listKind: NetReachList
    plural: netreaches
    shortNames:
    - nr
    singular: netreach
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: finish
      jsonPath: .status.finish
      name: finish
      type: boolean
    - description: expectedRound
      jsonPath: .status.expectedRound
      name: expectedRound
      type: integer
    - description: doneRound
      jsonPath: .status.doneRound
      name: doneRound
      type: integer
    - description: lastRoundStatus
      jsonPath: .status.lastRoundStatus
      name: lastRoundStatus
      type: string
    - description: schedule
      jsonPath: .spec.schedule.schedule
      name: schedule
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              expect:
                properties:
                  meanAccessDelayInMs:
                    default: 5000
                    format: int64
                    minimum: 1
                    type: integer
                  statusCode:
                    maximum: 599
                    minimum: 100
                    type: integer
                  successRate:
                    default: 1
                    maximum: 1
                    minimum: 0
                    type: number
                type: object
              request:
                properties:
                  durationInSecond:
                    default: 2
                    minimum: 1
                    type: integer
                  perRequestTimeoutInMS:
                    default: 5
                    minimum: 1
                    type: integer
                  qps:
                    default: 5
                    maximum: 100
                    minimum: 1
                    type: integer
                type: object
              schedule:
                properties:
                  roundNumber:
                    default: 1
                    format: int64
                    minimum: -1
                    type: integer
                  roundTimeoutMinute:
                    default: 60
                    format: int64
                    minimum: 1
                    type: integer
                  schedule:
                    type: string
                required:
                - roundNumber
                - roundTimeoutMinute
                type: object
              target:
                properties:
                  clusterIP:
                    default: true
                    type: boolean
                  enableLatencyMetric:
                    default: false
                    type: boolean
                  endpoint:
                    default: true
                    type: boolean
                  ingress:
                    default: false
                    type: boolean
                  ipv4:
                    default: true
                    type: boolean
                  ipv6:
                    default: false
                    type: boolean
                  loadBalancer:
                    default: false
                    type: boolean
                  multusInterface:
                    default: false
                    type: boolean
                  nodePort:
                    default: true
                    type: boolean
                type: object
            type: object
          status:
            properties:
              doneRound:
                format: int64
                minimum: 0
                type: integer
              expectedRound:
                format: int64
                minimum: -1
                type: integer
              finish:
                type: boolean
              history:
                items:
                  properties:
                    deadLineTimeStamp:
                      format: date-time
                      type: string
                    duration:
                      type: string
                    endTimeStamp:
                      format: date-time
                      type: string
                    expectedActorNumber:
                      description: expected how many agents should involve
                      type: integer
                    failedAgentNodeList:
                      items:
                        type: string
                      type: array
                    failureReason:
                      type: string
                    notReportAgentNodeList:
                      items:
                        type: string
                      type: array
                    roundNumber:
                      type: integer
                    startTimeStamp:
                      format: date-time
                      type: string
                    status:
                      enum:
                      - succeed
                      - fail
                      - ongoing
                      - notstarted
                      type: string
                    succeedAgentNodeList:
                      items:
                        type: string
                      type: array
                  required:
                  - deadLineTimeStamp
                  - failedAgentNodeList
                  - notReportAgentNodeList
                  - roundNumber
                  - startTimeStamp
                  - status
                  - succeedAgentNodeList
                  type: object
                type: array
              lastRoundStatus:
                enum:
                - succeed
                - fail
                - unknown
                type: string
            required:
            - finish
            - history
            type: object
        required:
        - metadata
        type: object
    served: true
    storage: true
    subresources:
      status: {}
