apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "project.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "project.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.kdoctorAgent.name | trunc 63 | trimSuffix "-" }}
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: {{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: {{ .Values.kdoctorController.apiserver.name | trunc 63 | trimSuffix "-" }}
    namespace: {{ .Release.Namespace }}
