name: Build Image CI

on:
  # called by daily build and push image
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      # ====modify====
      - images/agent/**
      - images/controller/**

permissions: write-all

jobs:
  call-by-workflow:
    uses: ./.github/workflows/call-release-image.yaml
    if: ${{ inputs.ref != '' }}
    with:
      ref: ${{ inputs.ref }}
      push: "false"
      upload: "true"
      race: "1"
    secrets: inherit

  call-by-pr:
    uses: ./.github/workflows/call-release-image.yaml
    if: ${{ github.event_name == 'pull_request_target' }}
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      push: "false"
      upload: "false"
      race: "1"
    secrets: inherit