name: Auto Update Golang Version

on:
  push:
    branches:
      - main
    paths:
      - 'Makefile.defs'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: update golang version
        run: |
          make update_go_version
          if ! test -z "$$(git status --porcelain)"; then
            echo "update golang"
            echo "RUN_UPDATE=true" >> $GITHUB_ENV
          else
             echo "no need to update golang version"
             echo "RUN_UPDATE=false" >> $GITHUB_ENV
          fi

      # https://github.com/peter-evans/create-pull-request
      - name: Create Pull Request
        id: create_pr
        if: ${{ env.RUN_UPDATE == 'true' }}
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          title: "robot Update project owing to updated Golang Version "
          commit-message: "robot Update project owing to updated Golang Version "
          branch-suffix: timestamp
          branch: robot/update_golang
          delete-branch: true
          base: main
          signoff: true
          token: ${{ secrets.WELAN_PAT }}
          labels: pr/robot_update
